---
# vars file for ukdigital-azure

# OpenShift resource group
azure_persistent_resource_group: "OpenShift-persistent-{{ env }}"
azure_resource_group: "OpenShift-infra-{{ env }}"


# key vault things
azure_ad_tenant: "850fb0fa-1e38-4247-a17b-ec99f97f20e9"
azure_ansible_app_id: "48d236ee-2cf5-4016-ad9c-08ff7214f608"
# Due to the 24char limit in Azure(FFS) one must do this mapping
azure_keyvault_name_mapping:
  prod: os-platform-prod
  non-prod: os-platform-np
azure_keyvault_name: "{{ azure_keyvault_name_mapping[env] }}"

# public keys
azure_deployment_public_keys: []

azure_hostname_prefix: ''

azure_os_choices:
  rhel73:
    publisher: RedHat
    offer: RHEL
    sku: "7.3"
    version: latest
  rhel74:
    publisher: RedHat
    offer: RHEL
    sku: "7-RAW"  # Yes this is in fact 7.4
    version: latest
  centos74:
    publisher: OpenLogic
    offer: CentOS
    sku: "7.4"
    version: latest

azure_nsg_old:

  ns:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-53"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "53"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
  alb:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 800
        direction: "Inbound"
    - name: "port-8443-from-vnet"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "8443"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 700
        direction: "Inbound"
  aom:
    - name: "port-111"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "111"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 960
        direction: "Inbound"
    - name: "port-1936"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "1936"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 950
        direction: "Inbound"
    - name: "port-2049"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2049"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 940
        direction: "Inbound"
    - name: "port-2379"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2379"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 930
        direction: "Inbound"
    - name: "port-2380"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2380"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 920
        direction: "Inbound"
    - name: "port-4194"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "4194"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-8080"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "8080"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 890
        direction: "Inbound"
    - name: "port-10250"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "10250"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 880
        direction: "Inbound"
    - name: "port-20048"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "20048"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 870
        direction: "Inbound"
    - name: "port-50825"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "50825"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 860
        direction: "Inbound"
    - name: "port-53248"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "53248"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 850
        direction: "Inbound"
    - name: "port-4789"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "4789"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 840
        direction: "Inbound"
    - name: "port-8053"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "8053"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 830
        direction: "Inbound"
    - name: "port-24224"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "24224"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 820
        direction: "Inbound"
  aon:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-10250"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "10250"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 990
        direction: "Inbound"
    - name: "port-4789"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "4789"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 980
        direction: "Inbound"
  ipa:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-53"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "53"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 800
        direction: "Inbound"
    - name: "port-88"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "88"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 700
        direction: "Inbound"
    - name: "port-389"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "389"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 600
        direction: "Inbound"
    - name: "port-443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 500
        direction: "Inbound"
    - name: "port-464"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "464"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 400
        direction: "Inbound"
    - name: "port-636"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "636"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 300
        direction: "Inbound"
    - name: "port-123"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "123"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 200
        direction: "Inbound"
  mtr:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"

# Network security groups:
# The idea is that we first deny than allow ports on top of our denials. In Azure this is done by assigning priorities
# The lower the number the higher the priority on the scale of: 1-65000
# The template auto-assigns priority in order of appearance in 2 ranges:
# Pirority:
#   100-30000 for Allow
#   30001-65000 for Deny
# The below example shows how to define rules:
#
#  ep:
#    Deny:
#      Inbound:
#        TCP: []
#        UDP: []
#      Outbound:
#        TCP: []
#        UDP: []
#    Allow:
#      Inbound:
#        TCP: []
#        UDP: []
#      Outbound:
#        TCP: []
#        UDP: []

azure_nsg:
  ep:
    Allow:
      Inbound:
        TCP:
          - sourcePortRange: "*"
            destinationPortRange: "22"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "80"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "443"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
        UDP:
          - sourcePortRange: "*"
            destinationPortRange: "1194"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
      Outbound:
        TCP: []
        UDP: []
    Deny:
      Inbound:
        TCP: []
        UDP: []
      Outbound:
        TCP: []
        UDP: []
  aom:
    Allow:
      Inbound:
        TCP:
          - sourcePortRange: "*"
            destinationPortRange: "22"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "80"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "443"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "8443"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "9090"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "111"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "1936"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "2049"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "2379"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "2380"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "4194"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "8080"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "10250"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "20048"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "50825"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "53248"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "8053"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "24224"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
        UDP:
          - sourcePortRange: "*"
            destinationPortRange: "4789"
            sourceAddressPrefix: "*"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "8053"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
          - sourcePortRange: "*"
            destinationPortRange: "24224"
            sourceAddressPrefix: "10.100.1.0/24"
            destinationAddressPrefix: "*"
      Outbound:
        TCP: []
        UDP: []
    Deny:
      Inbound:
        TCP: []
        UDP: []
      Outbound:
        TCP: []
        UDP: []

azure_lb:
  epLB:
    public_ip: true
    dns_name: "os-ep-{{env}}"
    private_ip: 10.100.254.11
    subnet: dmz1subnet
    probes:
      - protocol: tcp
        port: 80
        name: probe1
      - protocol: tcp
        port: 443
        name: probe2
    ports:
      - frontend: 80
        backend: 80
        protocol: tcp
        probe: probe1
      - frontend: 443
        backend: 443
        protocol: tcp
        probe: probe2
      - frontend: 1194
        backend: 1194
        protocol: udp
        probe: false
  appLB:
    public_ip: true
    dns_name: "os-app-{{env}}"
    private_ip: 10.100.254.12
    subnet: dmz1subnet
    probes:
      - protocol: tcp
        port: 80
        name: probe1
      - protocol: tcp
        port: 443
        name: probe2
      - protocol: tcp
        port: 8443
        name: probe3
    ports:
      - frontend: 80
        backend: 80
        protocol: tcp
        probe: probe1
      - frontend: 443
        backend: 443
        protocol: tcp
        probe: probe2
      - frontend: 8443
        backend: 8443
        protocol: tcp
        probe: probe3
