#all: # keys must be unique, i.e. only one 'hosts' per group
#    hosts:
#        test1:
#        test2:
#            var1: value1
#    vars:
#        group_var1: value2
#    children:   # key order does not matter, indentation does
#        other_group:
#            children:
#                group_x:
#                    hosts:
#                        test5
#            vars:
#                g2_var2: value3
#            hosts:
#                test4:
#                    ansible_host: 127.0.0.1
#        last_group:
#            hosts:
#                test1 # same host as above, additional group membership
#            vars:
#                last_var: MYVALUE

all:
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q cloud-user@os-ep01-non-prod.uksouth.cloudapp.azure.com"'
    static_inventory: true
  children:
    ep:
      hosts:
        ep01:
          ansible_host: 10.100.254.4
    ipa:
      hosts:
        ipa01:
          ansible_host: 10.100.100.11
          iparole: master
        ipa02:
          ansible_host: 10.100.100.12
          iparole: slave
    openshift:
      vars:
        openshift_disable_check:
          - disk_availability
          - docker_storage
          - docker_image_availability
        ansible_become: true
        openshift_deployment_type: origin
        deployment_type: origin
        containerized: true
        openshift_clock_enabled: true
        openshift_master_cluster_method: native
        openshift_master_cluster_hostname: 'os-app-non-prod.uksouth.cloudapp.azure.com'
        openshift_master_cluster_public_hostname: 'os-app-non-prod.uksouth.cloudapp.azure.com'

#        openshift_master_default_subdomain: 'mxrdnfpmxjeevivkjr2dmh2nmg.zx.internal.cloudapp.net'
        openshift_master_default_subdomain: 'os-app-non-prod.uksouth.cloudapp.azure.com'
        openshift_master_identity_providers:
          - name: htpasswd_auth
            login: true
            challenge: true
            kind: HTPasswdPasswordIdentityProvider
            filename: /etc/origin/master/htpasswd

      children:
        masters:
          hosts:
            aom01:
              ansible_host: 10.100.1.21
            aom02:
              ansible_host: 10.100.1.22
            aom03:
              ansible_host: 10.100.1.23
        nodes:
          hosts:
            aon01:
              ansible_host: 10.100.1.51
            aon02:
              ansible_host: 10.100.1.52
        etcd:
          hosts:
            aom01:
              ansible_host: 10.100.1.21
            aom02:
              ansible_host: 10.100.1.22
            aom03:
              ansible_host: 10.100.1.23
