---
# Copyright (c) 2017, Secnix Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL BIS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# https://github.com/ansible/ansible/pull/16138
#- name: Wait for reboot
#  delegate_to: "{{ golden_host }}"
#  wait_for:
#    host={{ inventory_hostname }}
#    port=22
#    poll=1
#    timeout=300

# Need to increase entropy as cloud providers generally don't have enough
# and this leads to exceptionally lengthy or incomplete installs.
- name: Install haveged
  yum: name=https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/haveged-1.9.1-1.el7.x86_64.rpm
       state=present

- name: Start haveged
  service: name=haveged state=started

- name: Install IPA server software
  yum: name={{ item }} state=present
  with_items: "{{ ipaserver_packages }}"

- name: Remove hostname resolving to 127.0.0.1
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1\s+{{ ansible_hostname }}'
              state=absent

- name: Insert IPA server hosts entry
  lineinfile: dest=/etc/hosts regexp="^{{ hostvars[item]['ansible_host'] }}" 
              line="{{ hostvars[item]['ansible_host'] }}\t{{ hostvars[item]['inventory_hostname'] }}.{{ ipaserver_domain }}\t{{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ groups['ipa'] }}"

- include: master.yaml
  when: "hostvars[inventory_hostname]['iparole'] == 'master'"
  tags:
    - masters

#- include: dnsentries.yaml
#  when: "hostvars[inventory_hostname]['iparole'] == 'master"
#  tags:
#    - dnsentries

- include: replica.yaml
  when: "hostvars[inventory_hostname]['iparole'] == 'replica'"
  tags:
    - replicas
