apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: gogs-pvc
  name: gogs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: gogs-pv
