apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-slave-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: xfs
    volumeID: 40c80bda-5ba4-41f6-b63d-f30ed3cb5f34
