apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-s2i-master-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: xfs
    volumeID: 61c03710-728c-409a-b07e-766b29d7877d
