apiVersion: v1
kind: Route
metadata:
  labels:
    app: jenkins
    template: jenkins-master
  name: jenkins
spec:
  host: jenkins.mgmt.{{ domain_name }}.test
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    host: jenkins.mgmt.{{ domain_name }}.test
    routerName: router
    wildcardPolicy: None
