apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mgmt-docker-registry
  name: mgmt-docker-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: mgmt-docker-registry-pv
