apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: nexus-pvc
  name: nexus-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: nexus-pv
