ipaserver_replicas: {}
ipaserver_configure_ssh: True
ipaserver_configure_sshd: True
ipaserver_dns_forwarder: False
ipaserver_domain: ukdigital.test
ipaserver_hbac_allow: True
ipaserver_idstart: 5000
ipaserver_idmax: False
ipaserver_mkhomedir: True
ipaserver_packages:
  - ipa-server-dns
ipaserver_realm: UKDIGITAL.TEST
ipaserver_setup_dns: True
ipaserver_setup_ntp: True
ipaserver_ssh_trust_dns: True
ipaserver_ui_redirect: True
ipaserver_manage_firewalld: True
ipaserver_keytab: /root/ukdigital.keytab
