---
# Copyright (c) 2017, Secnix Systems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL BIS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DMZ ports
- name: Create a port for the golden host
  azure_rm_networkinterface:
        name: dmzport11
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: dmz1subnet
        security_group_name: vpn
        security_group_name: external_ssh
        security_group_name: remote_repositories
        public_ip: no
        private_ip_address: 10.100.254.11

- name: Create ports for the external nameservers
  azure_rm_networkinterface:
        name: dmzport2{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: dmz1subnet
        security_group_name: remote_dns
        security_group_name: remote_repositories
        public_ip: no
        private_ip_address: 10.100.254.2{{ item }}
  with_sequence: start=1 count=2

# MGMT ports
- name: Create ports for the IPA servers
  azure_rm_networkinterface:
        name: mgmtport1{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: mgmt1subnet
        private_ip_address: 10.100.100.1{{ item }}
        public_ip: no
        security_group_name: mgmt_nodes
        security_group_name: ipa_server
        security_group_name: remote_repositories
  with_sequence: count=2

- name: Create ports for the monitoring servers
  azure_rm_networkinterface:
        name: mgmtport1{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: mgmt1subnet
        private_ip_address: 10.100.100.1{{ item }}
        public_ip: no
        security_group_name: mgmt_nodes
        security_group_name: internal_monitoring
        security_group_name: remote_repositories
  with_sequence: start=5 count=2

- name: Create private network ports for the monitoring servers
  azure_rm_networkinterface:
        name: mtrport1{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: mtr1subnet
        private_ip_address: 172.17.1.1{{ item }}
        public_ip: no
        security_group_name: private_monitoring
  with_sequence: start=5 count=2

# Load Balancer (HAProxy) ports
- name: Create app load balancer ports 
  azure_rm_networkinterface:
        name: appport0{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: app1subnet
        private_ip_address: 10.100.1.{{ item }}
        public_ip: no
        security_group_name: app_loadbalancer_nodes
        security_group_name: app_nodes
        security_group_name: remote_repositories
  with_sequence: start=5 count=2

- name: Create svc load balancer ports
  azure_rm_networkinterface:
        name: svcport0{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: svc1subnet
        private_ip_address: 10.100.20.{{ item }}
        public_ip: no
        security_group_name: svc_loadbalancer_nodes
        security_group_name: svc_nodes
        security_group_name: remote_repositories
  with_sequence: start=5 count=2

# APP ports
- name: Create a port for the app OpenShift master
  azure_rm_networkinterface:
        name: appport2{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: app1subnet
        private_ip_address: 10.100.1.2{{ item }}
        public_ip: no
        security_group_name: app_nodes
        security_group_name: remote_repositories
        security_group_name: app_openshift_master
  with_sequence: count=3

- name: Create a port for the app OpenShift nodes
  azure_rm_networkinterface:
      name: appport5{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: app1subnet
        private_ip_address: 10.100.1.5{{item }}
        public_ip: no
        security_group_name: app_nodes
        security_group_name: remote_repositories
        security_group_name: app_openshift_node
  with_sequence: count=2

# SVC ports
- name: Create a port for the svc OpenShift master
  azure_rm_networkinterface:
        name: svcport2{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: svc1subnet
        private_ip_address: 10.100.20.2{{ item }}
        public_ip: no
        security_group_name: svc_nodes
        security_group_name: remote_repositories
        security_group_name: svc_openshift_master
  with_sequence: count=3

- name: Create a port for the svc OpenShift nodes
  azure_rm_networkinterface:
        name: svcport5{{ item }}
        resource_group: {{ resource_group }}
        virtual_network_name: {{ virtual_network_name }}
        subnet_name: svc1subnet
        private_ip_address: 10.100.20.5{{ item }}
        public_ip: no
        security_group_name: svc_nodes
        security_group_name: remote_repositories
        security_group_name: svc_openshift_node
  with_sequence: count=2
